### ISSUE TITLE
Your licence plate is showing

### ISSUE THREAD

**Issue by lloydmeta** [tixxit/300zx#24]
Hey there,

Just wandered onto this public repo and saw that you have a photo of your car (nice car btw!) with its licence plate showing. Not sure that that's a good thing for privacy.

Feel free to close if not an issue :)

From a friendly Torontonian living in Tokyo.

**Comment by tixxit** [comment]
Haha - thanks! I wasn't horribly worried, but I suppose it doesn't hurt to just blur it out :)
